# Change these first
owner: duandaxei # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: $OWNER-$REPO
sites:
  - name: Public Relay Server - 0
    check: "tcp-ping"
    url: $SERVER0
    port: $PORT0
  - name: Public Relay Server - 1
    check: "tcp-ping"
    url: $SERVER1
    port: $PORT1
  - name: Public Relay Server - 2
    check: "tcp-ping"
    url: $SERVER2
    port: $PORT2
  - name: Public Relay Server - 3
    check: "tcp-ping"
    url: $SERVER3
    port: PORT3

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
